### PR TITLE
change omc interface from corba to direct

### PR DESCRIPTION
**Pull request by hkiel**

### CODE REVIEW

**Comment by hkiel** [comment]
@adeas31 @adrpo The OMShell-Terminal command line tool works fine, except that I need to explicitly define `CC=clang` environment variable. Without `CC` defined the tool crashes in
`omc_Main_init`->`omc_Main_setDefaultCC`->`omc_System_readEnv`->`System_readEnv`->longj`mp` with a segfault. Any idea on how to to `MMC_TRY` correctly? I just copied from OMNotebook...

The changes on OMShellGUI need the `CC=clang`, but also always produce a `EXC_BAD_INSTRUCTION` in `omc_Main_handleCommand`->`omc_Main_handleCommand2`->`omc_Interactive_evaluate`->`omc_Interactive_evaluate2`->`omc_Inst_initInstHashTable`->`omc_Inst_emptyInstHashTable`->`omc_BaseHashTable_emptyHashTableWork`->`GC_malloc_kind_global`->`GC_generic_malloc`->`GC_alloc_large`->`GC_collect_or_expand`->`_pthread_setcancelstate_internal`->`_os_unfair_lock_lock_slow`->`_os_unfair_lock_corruption_abort`
Seems to be a problem with GC and threads.

I'm working on macOS (OMNotebook and OMEdit are fine).

**Comment by sjoelund** [comment]
When dealing with Qt you need to make sure all running threads are registered with the GC or always call OM from the same thread (so not using Qt slots, etc). I think you need an MMC_TRY_TOP to initialize the top level or you might be using uninitialized data.

⁣Sent from BlueMail ​

**Comment by hkiel** [comment]
@adrpo I used `MMC_TRY_TOP_INTERNAL` like in OMEdit and OMNotebook, but that does not work out properly. I now removed modification of the `args` variable passed to `omc_Main_init()` and the code stopped crashing at later calls to `evalExpression()`. Still, `CC` needs to be set in environment, otherwise the function `Main.setDefaultCC` crashes on the `readEnv()` of
```
try
  System.setCCompiler(System.readEnv("CC"));
end try
```

@adeas31 I wonder what is different in OMEdit and OMNotebook (don't see any difference)

**Comment by sjoelund** [comment]
It might be locale settings. You need to be careful with those

⁣Sent from BlueMail ​

**Comment by hkiel** [comment]
@sjoelund `mosh` aka `OMShell-terminal` is neither threaded nor needs locale settings, but has problems with MMC_TRY (using the same code as e.g. OMNotebook!)
```
  modelica_metatype args = mmc_mk_nil();
  // enabling the following two lines leads to a crash (illegal instruction) in later calls to evalExpression()!!!
  //string locale = "+locale=C";
  //args = mmc_mk_cons(mmc_mk_scon(locale.c_str()), args);

  // initialize threadData
  threadData_t *threadData = (threadData_t *) calloc(2, sizeof(threadData_t));
  void *st = 0;
  MMC_TRY_TOP_INTERNAL()
  omc_Main_init(threadData, args); // needs env variable CC, else code will segfault in System_readEnv() when calling longjmp()
  st = omc_Main_readSettings(threadData, mmc_mk_nil());
  MMC_CATCH_TOP()
```

**Comment by sjoelund** [comment]
Tried to compile it to debug, but:
```
omcinteractiveenvironment.cpp:257:46: error: too many arguments to function call, expected single argument
      '__filename', have 3 arguments
      str.erase(std::remove(std::begin(str), std::end(str), ' '), std::end(str));
                ~~~~~~~~~~~                  ^~~~~~~~~~~~~~~~~~
/usr/include/stdio.h:178:1: note: 'remove' declared here
extern int remove (const char *__filename) __THROW;
```

The `using namespace std;` in the header messes things up for you since algorithm wasn't included and there is a name collision with the global namespace.

**Comment by sjoelund** [comment]
When I fix that, the shell executes as expected, except for a segmentation fault on program exit.

**Comment by hkiel** [comment]
I guess you are on Linux? Do you have CC environment variable defined???

**Comment by sjoelund** [comment]
No, I don't. I also tried the simulate some models and they work just fine (calling many longjmp).

**Comment by adeas31** [comment]
I think you forgot to call `MMC_INIT()`. It should work fine now.
I have also fixed the windows compilation.

**Comment by hkiel** [comment]
@adeas31 Ooops! Sorry, I somehow destroyed your changes. Can you check them in again, please?
I just wanted to add a change to mosh/src/mosh.cpp...

**Comment by hkiel** [comment]
@adeas31 I think I could recover the changes for windows (from OMNotebook).

**Pull request merged**
